"use client";
import { useMemo, useState } from "react";
import { ArrowRight, BookOpen, ChevronRight, Compass, Menu, Play, Search, Sparkles, Users, X } from "lucide-react";
import { categories, courses, values } from "../data/home";
const navigation = ["Главная", "Каталог", "Преподаватели", "Древо знаний", "Рейтинг", "Мессенджер", "О платформе"];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false); const [query, setQuery] = useState(""); const [notice, setNotice] = useState("");
  const shownCourses = useMemo(() => { const q=query.trim().toLowerCase(); return q ? courses.filter(c=>`${c.title} ${c.category}`.toLowerCase().includes(q)) : courses; }, [query]);
  const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenuOpen(false)};
  const tell=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),3000)};
  return <main>
    {notice && <div className="toast" role="status">{notice}</div>}
    <header className="header"><button className="brand" onClick={()=>go("top")} aria-label="SWITCH — на главную"><span className="brand-mark">S</span><span>SWITCH</span></button><nav className={menuOpen?"nav nav-open":"nav"} aria-label="Основная навигация">{navigation.map(item=><button key={item} className={item==="Главная"?"active":""} onClick={()=>item==="Главная"?go("top"):tell(`Раздел «${item}» появится на следующем этапе.`)}>{item}</button>)}</nav><div className="header-actions"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск навыков" aria-label="Поиск навыков" /></label><button className="login" onClick={()=>tell("Вход будет доступен в следующей версии интерфейса.")}>Войти</button><button className="button button-small" onClick={()=>tell("Добро пожаловать в SWITCH!")}>Регистрация</button><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Открыть меню">{menuOpen?<X/>:<Menu/>}</button></div></header>
    <section id="top" className="hero section"><div className="hero-copy"><p className="eyebrow"><span/>Взаимное обучение</p><h1>Учись. Делись.<br/><em>Развивайся.</em></h1><p className="hero-text">SWITCH — платформа, где люди обмениваются знаниями, развивают навыки и создают новые возможности вместе.</p><div className="hero-buttons"><button className="button" onClick={()=>go("skills")}>Начать бесплатно <ArrowRight size={18}/></button><button className="text-button" onClick={()=>go("how-it-works")}><span className="play"><Play size={13} fill="currentColor"/></span>Как это работает?</button></div></div><div className="hero-art" aria-label="Обмен знаниями"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-card art-card-top"><span className="tiny-avatar violet">А</span><div><b>Алексей</b><small>Python для начинающих</small></div><span className="hours">+1ч</span></div><div className="art-center"><Sparkles size={29}/><span>SWITCH<br/>Hours</span></div><div className="art-card art-card-bottom"><span className="tiny-avatar orange">М</span><div><b>Мария</b><small>Основы иллюстрации</small></div><span className="hours">+1ч</span></div><div className="art-note note-one">делись знаниями</div><div className="art-note note-two">открывай новое</div></div></section>
    <section id="how-it-works" className="value-wrap"><div className="section"><div className="section-heading"><p className="eyebrow"><span/>Почему SWITCH</p><h2>Знания объединяют<br/>и меняют траектории.</h2></div><div className="value-grid">{values.map((v,i)=>{const Icon=v.icon;return <article className="value-card" key={v.title}><span className="value-number">0{i+1}</span><div className="icon-box"><Icon size={21}/></div><h3>{v.title}</h3><p>{v.description}</p><button onClick={()=>tell(`${v.title}: подробнее — на странице «О платформе».`)} aria-label={`Подробнее: ${v.title}`}><ChevronRight size={19}/></button></article>})}</div></div></section>
    <section className="section categories-section"><div className="section-heading row-heading"><div><p className="eyebrow"><span/>Исследуйте направления</p><h2>Найдите то, что<br/>вам интересно.</h2></div><button className="all-link" onClick={()=>tell("Каталог навыков будет доступен на следующем этапе.")}>Все направления <ArrowRight size={17}/></button></div><div className="categories">{categories.map(c=><button key={c.name} className="category" onClick={()=>tell(`Направление «${c.name}» выбрано.`)}><span className={`category-icon ${c.color}`}>{c.icon}</span><span>{c.name}</span><ArrowRight size={17}/></button>)}</div></section>
    <section id="skills" className="section skills-section"><div className="section-heading row-heading"><div><p className="eyebrow"><span/>Начните с малого</p><h2>Рекомендуем<br/>для вас.</h2></div><p className="side-copy">Выберите навык, которым давно хотели заняться — и найдите человека, готового поделиться опытом.</p></div><div className="course-grid">{shownCourses.map(c=><article className="course-card" key={c.title}><div className={`course-cover ${c.cover}`}><span>{c.category}</span><div className="cover-symbol">{c.symbol}</div></div><div className="course-info"><div className="course-meta"><span>{c.level}</span><span>{c.duration}</span></div><h3>{c.title}</h3><p>от {c.teacher}</p><button onClick={()=>tell(`Запрос на обучение «${c.title}» отправлен.`)}>Подробнее <ArrowRight size={16}/></button></div></article>)}</div>{shownCourses.length===0&&<p className="empty-state">По этому запросу пока ничего не нашли. Попробуйте другое слово.</p>}</section>
    <section className="section cta"><div><p className="eyebrow light"><span/>Ваш следующий шаг</p><h2>Знания сегодня —<br/><em>большие возможности</em><br/>завтра.</h2></div><div className="cta-side"><p>Начните учиться, делиться и находить своих людей в сообществе SWITCH.</p><button className="button light-button" onClick={()=>tell("Ваше знакомство с SWITCH начинается здесь.")}>Присоединиться <ArrowRight size={18}/></button></div></section>
    <footer><button className="brand" onClick={()=>go("top")}><span className="brand-mark">S</span><span>SWITCH</span></button><p>Платформа взаимного обучения и развития.</p><span>© 2026 SWITCH</span></footer>
  </main>;
}
