"use client";

import { useState } from "react";
import { ArrowRight, Award, BookOpen, CalendarDays, Check, ChevronRight, CircleDollarSign, Clock3, Filter, GraduationCap, Mail, Medal, MessageCircle, Search, Send, Settings, Sparkles, Star, Users, Wallet } from "lucide-react";
import { AppShell } from "./AppShell";
import { SiteLink } from "./SiteLink";

const teachers=[['Алексей Петров','Python','Advanced','4.9','Сегодня после 18:00','А'],['Мария Соколова','Иллюстрация','Advanced','4.8','Завтра','М'],['Елена Воронова','Английский язык','Upper-intermediate','4.9','В пятницу','Е'],['Иван Морозов','Фотография','Intermediate','4.7','На этой неделе','И']];
const skills=[['Python для начинающих','Программирование','Начинающий','Онлайн','4.9'],['UI/UX: основы интерфейса','Дизайн и творчество','Начинающий','Онлайн','4.8'],['Разговорный английский','Языки','Средний','Гибрид','4.9'],['Фотография в городе','Фото и видео','Начинающий','Очно','4.7'],['Личный бюджет','Бизнес и финансы','Начинающий','Онлайн','4.8'],['Основы C','Программирование','Средний','Онлайн','4.7']];
const operations=[['+1.0','Проведено занятие Python','Сегодня','earned'],['−1.5','Занятие по английскому языку','18 сентября','spent'],['+15','Награда за 1 место в рейтинге месяца','1 сентября','earned'],['+1.0','Проведено занятие C','29 августа','earned']];

function Page({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <AppShell><main className="product-page"><div className="page-title"><p className="eyebrow"><span/>{kicker}</p><h1>{title}</h1></div>{children}</main></AppShell>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <article className={`ui-card ${className}`}>{children}</article>}
const Button=({children,href="#"}:{children:React.ReactNode;href?:string})=><SiteLink className="small-button" href={href}>{children}<ArrowRight size={16}/></SiteLink>;

export function CatalogPage(){const [filter,setFilter]=useState('Все');const cats=['Все','Программирование','Дизайн','Языки','Бизнес','Фото и видео'];const shown=filter==='Все'?skills:skills.filter(s=>s[1].includes(filter)|| (filter==='Дизайн'&&s[1].includes('Дизайн')));return <Page title="Каталог навыков" kicker="Исследуйте возможности"><div className="toolbar"><label className="wide-search"><Search size={18}/><input placeholder="Что вы хотите изучить?"/></label><button className="filter-button"><Filter size={17}/>Фильтры</button></div><div className="chips">{cats.map(c=><button className={filter===c?'selected':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="skill-grid">{shown.map(s=><Card key={s[0]}><div className="skill-icon"><BookOpen size={23}/></div><p className="meta">{s[1]}</p><h3>{s[0]}</h3><div className="tags"><span>{s[2]}</span><span>{s[3]}</span></div><p className="rating"><Star size={14} fill="currentColor"/>{s[4]} <small>рейтинг</small></p><Button href="/teachers">Найти преподавателя</Button></Card>)}</div></Page>}

export function TeachersPage(){return <Page title="Преподаватели" kicker="Учитесь у практиков"><div className="intro-row"><p>Люди, которые готовы поделиться опытом и помочь сделать следующий шаг.</p><label className="compact-search"><Search size={16}/><input placeholder="Поиск преподавателя"/></label></div><div className="teacher-grid">{teachers.map(t=><Card key={t[0]} className="teacher-card"><div className="avatar large-avatar">{t[5]}</div><div><h3>{t[0]}</h3><p className="meta">{t[1]} · {t[2]}</p></div><p className="rating"><Star size={14} fill="currentColor"/>{t[3]}</p><p className="availability"><i/> {t[4]}</p><div className="card-actions"><Button href="/profile">Профиль</Button><SiteLink href="/messages" className="outline-button"><MessageCircle size={16}/>Написать</SiteLink></div></Card>)}</div></Page>}

export function ProfilePage(){return <Page title="Мой профиль" kicker="Личная траектория"><section className="profile-hero"><div className="avatar profile-avatar">О</div><div><h2>Ольга Смирнова</h2><p>Люблю разбирать сложное по шагам и верю, что знания становятся ценнее, когда ими делятся.</p><span className="location">Москва · Участник SWITCH</span></div><div className="profile-badges"><span>SWITCH Level <b>06</b></span><span><Wallet size={16}/>8.5 Hours</span><span><Star size={16} fill="currentColor"/>4.9</span></div></section><div className="stats-row">{[['25','часов преподавания'],['18','учеников'],['3','изучаемых навыка'],['65','Knowledge Impact']].map(x=><Card key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></Card>)}</div><section className="two-col"><div><h2>Я могу научить</h2>{[['Python','Advanced','4.9','18 часов'],['C','Intermediate','4.7','7 часов']].map(s=><Card key={s[0]} className="skill-row"><div className="skill-icon">{s[0][0]}</div><div><h3>{s[0]}</h3><p>{s[1]} · Рейтинг {s[2]}</p></div><b>{s[3]}</b></Card>)}</div><div><h2>Я хочу изучить</h2><Card><div className="interest-list">{['UI/UX','Фотография','Английский язык'].map(x=><span key={x}>{x}<ChevronRight size={16}/></span>)}</div></Card><Card className="tree-preview"><p className="eyebrow"><span/>Моё древо знаний</p><div className="mini-tree"><span>Наставник</span><i/><b>Ольга</b><i/><span>18 учеников</span></div><Button href="/knowledge-tree">Открыть древо</Button></Card></div></section></Page>}

export function WalletPage(){return <Page title="SWITCH Hours" kicker="Время — главная валюта"><section className="wallet-hero"><div><p>Ваш текущий баланс времени</p><strong>8.5</strong><span>SWITCH Hours</span></div><Clock3 size={55}/></section><p className="wallet-note">SWITCH Hours нельзя купить. Они зарабатываются через передачу знаний другим участникам платформы.</p><h2 className="block-title">История операций</h2><div className="operation-list">{operations.map(o=><Card key={o[1]} className="operation"><div className={`operation-icon ${o[3]}`}><Clock3 size={18}/></div><div><h3>{o[1]}</h3><p>{o[2]} · {o[3]==='earned'?'Получено':'Списано'}</p></div><b className={o[3]}>{o[0]} SWITCH {o[0]==='+1.0'?'Hour':'Hours'}</b></Card>)}</div></Page>}

export function RatingsPage(){const [tab,setTab]=useState('Общий');return <Page title="Рейтинг" kicker="Вклад в сообщество"><div className="tabs">{['Общий','По навыкам','Рейтинг месяца'].map(t=><button onClick={()=>setTab(t)} className={tab===t?'active':''} key={t}>{t}</button>)}</div>{tab==='Рейтинг месяца'?<><section className="month-hero"><Medal size={43}/><div><p>Рейтинг месяца · сентябрь</p><h2>Ваше место: <b>4</b></h2></div><span>До тройки лидеров — 3 Hours</span></section><div className="prizes">{[['1 место','+15 SWITCH Hours'],['2 место','+12 SWITCH Hours'],['3 место','+10 SWITCH Hours']].map((x,i)=><Card key={x[0]}><Medal size={24}/><b>{x[0]}</b><span>{x[1]}</span></Card>)}</div></>:null}<div className="rank-list">{[['1','Мария Соколова','41.5'],['2','Алексей Петров','38.0'],['3','Елена Воронова','34.5'],['4','Ольга Смирнова','31.0'],['5','Иван Морозов','28.0']].map(r=><Card className={r[0]==='4'?'me':''} key={r[0]}><b className="place">{r[0]}</b><span className="avatar">{r[1][0]}</span><h3>{r[1]}</h3><span>{r[2]} Hours</span></Card>)}</div></Page>}

export function TreePage(){return <Page title="Древо знаний" kicker="Влияние, которое растёт"><div className="tree-toolbar"><button>Python <ChevronDown size={16}/></button><p>Как знания передаются от человека к человеку.</p></div><section className="tree-graph"><div className="tree-node mentor">Наставник<br/><b>Алексей</b></div><i/><div className="tree-node me">Ольга</div><i/><div className="tree-branch"><div className="tree-node">Ученик 1</div><div className="tree-node">Ученик 2</div></div></section><div className="impact-grid">{[['18','Личные ученики'],['7','Продолжили передавать знания'],['46','Получили знания через мою ветку'],['4','Глубина · поколения'],['65','Knowledge Impact']].map(x=><Card key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></Card>)}</div></Page>}

export function AchievementsPage(){const groups=[['Полученные',['Лучший наставник месяца','10 часов преподавания','Первые 5 учеников']],['В процессе',['30 дней активности','Knowledge Impact 100']],['Редкие',['Первые переданные знания']]];return <Page title="Награды" kicker="Отмечайте свой путь"><div className="achievement-groups">{groups.map(g=><section key={g[0]}><h2>{g[0]}</h2><div className="achievement-grid">{g[1].map((x,i)=><Card key={x} className={g[0]==='Полученные'?'earned-badge':''}><Award size={28}/><h3>{x}</h3><p>{g[0]==='В процессе'?'Осталось совсем немного':'Достижение SWITCH'}</p>{g[0]==='В процессе'&&<div className="progress"><i style={{width:`${55+i*18}%`}}/></div>}</Card>)}</div></section>)}</div></Page>}

export function MessagesPage(){const [message,setMessage]=useState('');const [messages,setMessages]=useState(['Добрый день, Ольга! Готов обсудить занятие по Python.','Здравствуйте! Да, мне удобно в четверг после 18:00.']);return <Page title="Мессенджер" kicker="Общайтесь и договаривайтесь"><section className="messenger"><aside><label className="compact-search"><Search size={16}/><input placeholder="Поиск диалогов"/></label>{teachers.slice(0,3).map((t,i)=><button className={i===0?'dialog selected-dialog':'dialog'} key={t[0]}><span className="avatar">{t[5]}</span><span><b>{t[0]}</b><small>{i===0?'Договоримся о времени':'Спасибо за занятие!'}</small></span></button>)}</aside><div className="chat"><header><span className="avatar">А</span><div><b>Алексей Петров</b><small>Python · Advanced</small></div></header><div className="bubbles">{messages.map((m,i)=><p key={i} className={i%2?'own':''}>{m}</p>)}</div><form onSubmit={e=>{e.preventDefault();if(message.trim()){setMessages([...messages,message]);setMessage('')}}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Напишите сообщение"/><button aria-label="Отправить"><Send size={18}/></button></form></div><aside className="chat-info"><span className="avatar large-avatar">А</span><h3>Алексей Петров</h3><p>Python · Advanced</p><p><Star size={14} fill="currentColor"/> 4.9 рейтинг</p><Card><CalendarDays size={18}/><span>Ближайшее занятие<br/><b>Четверг, 18:00</b></span></Card></aside></section></Page>}

export function CalendarPage(){const [view,setView]=useState('Неделя');return <Page title="Календарь" kicker="Ваше время"><div className="tabs calendar-tabs">{['День','Неделя','Месяц'].map(x=><button className={view===x?'active':''} onClick={()=>setView(x)} key={x}>{x}</button>)}</div><section className="calendar-card"><header><button>‹</button><h2>16–22 сентября</h2><button>›</button></header><div className="calendar-grid">{['Пн 16','Вт 17','Ср 18','Чт 19','Пт 20','Сб 21','Вс 22'].map((d,i)=><div key={d}><b>{d}</b>{i===1&&<p className="event purple-event">18:00<br/>Python · Алексей</p>}{i===3&&<p className="event peach-event">19:30<br/>Английский · Елена</p>}{i===5&&<p className="event green-event">12:00<br/>UI/UX · Мария</p>}</div>)}</div></section></Page>}

export function SettingsPage(){return <Page title="Настройки" kicker="Ваше пространство"><div className="settings-list">{[['Профиль','Имя, город и краткое описание'],['Уведомления','Напоминания о занятиях и сообщениях'],['Приватность','Видимость профиля и навыков']].map(x=><Card key={x[0]}><Settings size={19}/><div><h3>{x[0]}</h3><p>{x[1]}</p></div><ChevronRight size={18}/></Card>)}</div></Page>}
